before_script:
  - apt-get update -qq
  - apt-get install -y --no-install-recommends qpdf
  - apt-get install -y libglu1-mesa-dev

r-base:
   stage: test
   image: rocker/tidyverse
   script:
    - Rscript -e 'devtools::install_dev_deps()'
    - Rscript -e 'devtools::check()'
