image: rocker/tidyverse

before_script:
  - apt-get install -y libglu1-mesa-dev

test:  
   script:
    - R -e 'install.packages(c("desplot", "emmeans", "fields", "lme4", "qtl", "SpATS"))'
    - R CMD build . --no-build-vignettes --no-manual
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual