stages:
  - build

image: docker-registry.wur.nl/rossu027/r-verasreml:latest

variables:
  R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib"

before_script:
  ## Add R_LIBS_USER to libpaths.
  - echo '.libPaths("'${R_LIBS_USER}'")' > .Rprofile
  ## set GITLAB_PAT.
  - echo 'GITLAB_PAT='$GITLAB_PAT > .Renviron

R-devel:
  stage: build
  image: docker-registry.wur.nl/rossu027/r-develasreml:latest
  allow_failure: true
  script:
    - Rscriptdevel -e 'sessionInfo()'
    ## Install missing and outdated packages.
    - Rscriptdevel -e 'source(".gitlab-ci.R"); pkgsUpdate()'
    ## Build package.
    - Rdevel CMD build . --no-manual
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - Rdevel CMD check "${PKG_FILE_NAME}" --no-manual --as-cran
  artifacts:
    when: always
    paths:
      - '*.Rcheck/*'
    expire_in: '1 month'
  cache:
    key: devel-cache
    paths:
      - $R_LIBS_USER


