before_script:
  - apt-get update -qq
  - apt-get install -y --no-install-recommends qpdf
  - apt-get install -y libglu1-mesa-dev
  - export _R_CHECK_FORCE_SUGGESTS_="false"

r-base:
   stage: test
   image: rocker/tidyverse
   script:
    - Rscript -e 'devtools::install_dev_deps()'
    - R CMD build . --no-build-vignettes --no-manual
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}" --as-cran --no-tests
    - Rscript -e 'res<-devtools::test(reporter="summary");df<-as.data.frame(res);if(sum(df$failed) > 0 || any(df$error)) {q(status=1)}'
